[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = true

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[browser]
gatherUsageStats = false
